"""Condensed five-industry dataset (medical, legal, e-commerce, short-video, map listings).

    python mixed/generate.py           -> writes mixed/seed.sql
    python mixed/generate.py --check   -> regenerates and diffs (exit 1 on drift)

Each industry contributes only the tables its questions need. Table names are
prefixed (med_, leg_, ecom_, tt_, map_) so five schemas can share one database.
Data is produced by the unmodified per-industry generators in mixed/sources/,
so every injected defect is exactly the one documented for that industry.
Bump DATASET_VERSION whenever the selection or any source generator changes.
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path

DATASET_VERSION = "1.0.0"
HERE = Path(__file__).parent

# industry -> (prefix, tables kept, in load order)
KEEP = {
    "medical": ("med_", ["departments", "admissions", "lab_items", "lab_events", "prescriptions"]),
    "legal": ("leg_", ["cases", "parties", "docket_entries", "fee_invoices"]),
    "ecommerce": ("ecom_", ["warehouses", "products", "customers", "orders", "payments", "shipments"]),
    "tiktok": ("tt_", ["creators", "users", "videos", "likes", "reports", "promotions"]),
    "maps": ("map_", ["owners", "places", "reviews", "flags"]),
}


def load(name: str):
    spec = importlib.util.spec_from_file_location(f"{name}_generate", HERE / "sources" / f"{name}_generate.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def table_ddls(name: str, prefix: str, kept: list[str]) -> dict[str, str]:
    """Extract CREATE TABLE statements for kept tables, renamed with the prefix."""
    text = (HERE / "sources" / f"{name}_schema.sql").read_text()
    out = {}
    for m in re.finditer(r"CREATE TABLE (\w+) \(.*?\n\) ENGINE=[^;]*;", text, re.S):
        tbl, ddl = m.group(1), m.group(0)
        if tbl not in kept:
            continue
        ddl = ddl.replace(f"CREATE TABLE {tbl} (", f"CREATE TABLE {prefix}{tbl} (", 1)

        def fix_comment(cm):
            ref_tbl, ref_col = cm.group(1), cm.group(2)
            if ref_tbl in kept:
                return f" COMMENT '{prefix}{ref_tbl}.{ref_col}'"
            return ""  # reference to a table that is not part of this dataset

        ddl = re.sub(r" COMMENT '(\w+)\.(\w+)'", fix_comment, ddl)
        out[tbl] = ddl
    return out


def generate() -> str:
    parts = [
        f"-- Condensed five-industry dataset v{DATASET_VERSION}.",
        "-- GENERATED by mixed/generate.py from mixed/sources/. Do not edit by hand.",
        "-- No FOREIGN KEY constraints on purpose (see defect D8).",
    ]
    ddls, inserts = [], []
    for name, (prefix, kept) in KEEP.items():
        mod = load(name)
        ddl = table_ddls(name, prefix, kept)
        tables = mod.build_tables()
        for t in kept:
            ddls.append(ddl[t])
            cols, rows = tables[t]
            inserts.append(f"-- {prefix}{t}: {len(rows)} rows")
            inserts.extend(mod.insert_stmts(prefix + t, cols, rows))
    for name, (prefix, kept) in KEEP.items():
        parts.extend(f"DROP TABLE IF EXISTS {prefix}{t};" for t in kept)
    parts.extend(ddls)
    parts += ["SET autocommit = 0;", "START TRANSACTION;"] + inserts + ["COMMIT;", "SET autocommit = 1;"]
    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="diff against committed seed.sql")
    args = ap.parse_args()
    text = generate()
    out = HERE / "seed.sql"
    if args.check:
        if not out.exists() or out.read_text() != text:
            print("seed.sql is out of date; rerun generate.py", file=sys.stderr)
            return 1
        print("seed.sql is up to date")
        return 0
    out.write_text(text)
    print(f"wrote {out} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
